### PR TITLE
alpine/3.5.*: compatible with environment config

### PR DESCRIPTION
**Pull request by hervenicol**
**New feature:**

Added functionnality: you can override ArangoDB config with environment variables.
This to follow 12-factors principles: https://12factor.net/config

Here is the syntax:
```
env vars syntax:
 ARANGOCONF_SECTION_PARAMETER=VALUE
example:
 ARANGOCONF_LOG_LEVEL=debug
  => update [log] section with "level = debug"
```

**Questions:**
* This patch applies only to alpine/3.5.* containers. But the code is POSIX-compliant, and should run on any sh implementation.
Is there was a _master_ entrypoint to apply the changes to, or was I right in applying my updates to some specific versions of the entrypoint ?

* I'd be glad to update the doc with this new feature, but I did not find it. I guess it's on the docker hub directly ?

### CODE REVIEW

**Comment by OmarAyo** [comment]
Hi @hervenicol 

Many thanks for contributing. We are obliged by law to have a signed scanned copy of a Contributor License Agreement (CLA) to be able to accept pull requests to the official ArangoDB repository 

We use an Apache 2 CLA for ArangoDB and its companion projects, which can be found here: https://www.arangodb.com/documents/cla.pdf
Just fill in the form, sign and send a scanned copy over to cla@arangodb.com

Thank you

**Comment by OmarAyo** [comment]
CLA available

**Comment by dothebart** [comment]
Hi, several remarks. 
 - the files that you patch are autogenerated [copied] from https://github.com/arangodb/oskar/blob/master/containers/arangodb35.docker/entrypoint.sh - so a PR should be made there. I will update the TL Readme accordingly. 
 - the docker library points to certain git revision, so changing already released files will not change anything
 - can you elaborate a little more about the motivations for this PR? as you probably saw the entrypoint script forwards `$@` to `arangod`, so as explained in https://www.arangodb.com/docs/stable/administration-configuration.html you can allso set all configuration values via the cmdline.

**Comment by hervenicol** [comment]
Hi, thanks for your answers.

I will create a PR the master entrypoint in oskar repository, and elaborate the reasons there.

**Pull request closed without merging**
