### PR TITLE
fixed erroneous permissions for /tmp/arangodb

### PR DESCRIPTION
**Pull request by EdwarDDay**
When downloading or uploading a Foxx app into the database, arangodb lacks proper permissions to write into /tmp/arangodb. This small change fixes this.

### CODE REVIEW

**Comment by pluma** [comment]
+1 @fceller This is currently breaking Foxx on ArangoDB 2.6.9 from docker, too.

**Comment by fceller** [comment]
I think it was an error to create "/tmp/arangodb" in the standalone script in the first place. I've fixed this, can you try again?

**Comment by EdwarDDay** [comment]
Your fix solved the problem.

**Comment by fceller** [comment]
@EdwarDDay thanks for checking.

**Pull request closed without merging**
