### PR TITLE
Removed duplicate -d in docker run command.

### PR DESCRIPTION
**Pull request by chiliburger**
Removed duplicate -d in docker run command in the README.md file.

### CODE REVIEW

**Comment by fceller** [comment]
@chiliburger sorry for the long delay and thanks a lot for spotting the typo.

We were currently trying to setup an automated CLA process, which failed. We would like to use an Apache Contributor like License. Would it be possible for you to sign https://www.arangodb.com/documents/cla.pdf manually? While in principle it is not required for a simple bug fix, it avoids any discussion if we want to fulfill the Apache 2 requirements.

**Comment by chiliburger** [comment]
@fceller no problem. I can sign the doc manually.

**Comment by chiliburger** [comment]
@fceller signed and sent via email. Thanks!

**Comment by fceller** [comment]
@chiliburger thanks a lot and sorry for the inconvenience.

**Comment by chiliburger** [comment]
@fceller no problem!

**Pull request merged**
