### PR TITLE
Add -R for recursive chgrp and chmod to support OpenShift

### PR DESCRIPTION
**Pull request by vpavlin**
This fixes issue reported in #57 

I am not 100 % sure how you want to do these changes (whether in all templates like I did here, or just the 3.4 template), but review this, please, and let me know if you need any changes.

### CODE REVIEW

**Comment by OmarAyo** [comment]
Hi @vpavlin 

Thanks a lot for your contribution

For legal reasons we need you to fill out and sign our Contributor License Agreement (CLA). You can scan and email the CLA PDF file to cla@arangodb.com or send it via fax to +49-221-2722999-88.

We are using a Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

Best,

**Comment by vpavlin** [comment]
Hi @OmarAyo, sorry for late response, I have rebased the branch and sent the signed CLA. Let me know

**Comment by OmarAyo** [comment]
Hi @vpavlin,

We have received your signed CLA, many thanks again for your contribution

Best,

**Comment by vpavlin** [comment]
What is the process now to get it merged?

**Comment by OmarAyo** [comment]
Hi @vpavlin,

Now the ArangoDB engineering team will review your PR and decide whether to go ahead and merge it or not. 

Best,

**Review by fceller — APPROVED** [review]

**Pull request merged**
